
import { Estacion } from './estaciones';

export const ESTACIONES: Array<Estacion> = [
  new Estacion('la-pinilla', 'La Pinilla', 23, 15.57, 4, 6, 13, 13, 35, 26, 65, 48, 140, 89,
  // tslint:disable-next-line:max-line-length
  'Plano La Pinilla', './assets/plano_lapinilla.jpg', 'La estación de esquí de La Pinilla está situada en la Sierra de Ayllón del Sistema Central. Pertenece al término municipal de Cerezo de Arriba, en la provincia de Segovia, comunidad autónoma de Castilla y León, España.'),
  // tslint:disable-next-line:max-line-length
  new Estacion('puerto-navacerrada', 'Puerto de Navacerrada', 8, 6.2, 1, 3, 1, 7, 27, 27, 50, 50, 140, 140, 'Plano Navacerrada', './assets/plano_navacerrada.jpg', 'Es una antigua estación de esquí ubicada en el límite de las provincias de Madrid y Segovia cuyas pistas discurren en la boscosa zona de los valles de Valsaín y Navalmedio. Tiene dos zonas de esquí diferenciadas: Zona de debutantes, con pistas cortas más sencillas y protegida climatológicamente, ideal para los principiantes en la práctica del esquí. Está en el lado oeste del puerto de montaña y las pistas están dentro de un hermoso bosque de pino silvestre. Algunas de las pistas y remontes de esta zona están dentro de la provincia de Segovia. Hay también una pequeña pista reservada a los trineos. Zona de nivel alto, con pistas rojas de mayor dificultad que por su ubicación normalmente permanecen cerradas y algunas en desuso. Está en el lado este del puerto de montaña y las pistas están en una zona cubierta de matorrales rastreros como el piorno y el enebro. Algunas de las pistas y remontes de esta zona están dentro de la provincia de Segovia. El telesilla de Guarramillas permanece abierto los fines de semana de los meses de primavera, verano y otoño, de manera que también tiene un uso turístico.'),
  // tslint:disable-next-line:max-line-length
  new Estacion('sierra-bejar', 'Sierra de Béjar', 24, 20.29, 3, 6, 15, 4, 29, 20, 54, 38, 130, 120, 'Plano Bejar', './assets/plano_sierra_bejar.jpg', 'La Sierra de Béjar es de una de las comarcas con mayor sentido histórico-tradicional, geográfico y cultural de la provincia de Salamanca, en Castilla y León, España,1​2​ aunque sus límites no se corresponden con una división administrativa. Su parte más elevada hace de límite con las provincias de Ávila y Cáceres por lo que en las comarcas cacereñas del Valle del Jerte y el Valle del Ambroz así como en la abulense del Alto Tormes también se usa el topónimo Sierra de Béjar para referirse a las vertientes de esta sierra en dichas provincias.'),
  // tslint:disable-next-line:max-line-length
  new Estacion('valdesqui', 'Valdesqui', 26, 22.24, 8, 14, 4, 15, 38, 32, 70, 60, 160, 150, 'Plano Valdesqui', './assets/plano_valdesqui.jpg', 'Valdesquí es una estación de esquí que está situada en la Sierra de Guadarrama (sierra perteneciente al Sistema Central), en la ladera norte de las montañas de la Bola del Mundo y el Cerro de Valdemartín. Se ubica en el término municipal de Rascafría, en el noroeste de la Comunidad de Madrid (España). A pesar de que su superficie esquiable de 220 hectáreas es pequeña si se la compara con otras de los Pirineos o los Alpes, es la más grande y transitada de toda la sierra y la Comunidad de Madrid. Tiene 22 km esquiables, 21 remontes, y acceso por carretera desde Segovia y Madrid. El ferrocarril de Cotos no llega hasta la estación, estando la estación de Cotos a 2,7 km.')
];

